/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourneesRouteImport } from './routes/tournees'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SaisieTraficRouteImport } from './routes/saisie-trafic'
import { Route as SaisieTerrainRouteImport } from './routes/saisie-terrain'
import { Route as IndexRouteImport } from './routes/index'

const TourneesRoute = TourneesRouteImport.update({
  id: '/tournees',
  path: '/tournees',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieTraficRoute = SaisieTraficRouteImport.update({
  id: '/saisie-trafic',
  path: '/saisie-trafic',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieTerrainRoute = SaisieTerrainRouteImport.update({
  id: '/saisie-terrain',
  path: '/saisie-terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
  '/saisie-trafic': typeof SaisieTraficRoute
  '/support': typeof SupportRoute
  '/tournees': typeof TourneesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
  '/saisie-trafic': typeof SaisieTraficRoute
  '/support': typeof SupportRoute
  '/tournees': typeof TourneesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
  '/saisie-trafic': typeof SaisieTraficRoute
  '/support': typeof SupportRoute
  '/tournees': typeof TourneesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saisie-terrain'
    | '/saisie-trafic'
    | '/support'
    | '/tournees'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saisie-terrain' | '/saisie-trafic' | '/support' | '/tournees'
  id:
    | '__root__'
    | '/'
    | '/saisie-terrain'
    | '/saisie-trafic'
    | '/support'
    | '/tournees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SaisieTerrainRoute: typeof SaisieTerrainRoute
  SaisieTraficRoute: typeof SaisieTraficRoute
  SupportRoute: typeof SupportRoute
  TourneesRoute: typeof TourneesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournees': {
      id: '/tournees'
      path: '/tournees'
      fullPath: '/tournees'
      preLoaderRoute: typeof TourneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie-trafic': {
      id: '/saisie-trafic'
      path: '/saisie-trafic'
      fullPath: '/saisie-trafic'
      preLoaderRoute: typeof SaisieTraficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie-terrain': {
      id: '/saisie-terrain'
      path: '/saisie-terrain'
      fullPath: '/saisie-terrain'
      preLoaderRoute: typeof SaisieTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SaisieTerrainRoute: SaisieTerrainRoute,
  SaisieTraficRoute: SaisieTraficRoute,
  SupportRoute: SupportRoute,
  TourneesRoute: TourneesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
